P8105 hw2
================
Jiawei Ye

Problem 1
---------

The following code chunk reads the data and do some cleaning.

``` r
data_read = read.csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>% 
  janitor::clean_names()
nyc_transit = select(data_read, line:vending, ada, -exit_only) %>% 
  mutate(entry = recode(entry,"YES" = TRUE, "NO" = FALSE))
names(nyc_transit)
```

    ##  [1] "line"              "station_name"      "station_latitude" 
    ##  [4] "station_longitude" "route1"            "route2"           
    ##  [7] "route3"            "route4"            "route5"           
    ## [10] "route6"            "route7"            "route8"           
    ## [13] "route9"            "route10"           "route11"          
    ## [16] "entrance_type"     "entry"             "vending"          
    ## [19] "ada"

The above code chunk retained variables about the station and discarded the variables about the entrances of the station. It also changed the value of `entry` variable into logical value. The dimension of the dataset is 1868 rows and 19 columns.

Each observation in the dataset is a subway station entrances/exits in NYC, the variables describe stations name of the entrance/exit, the routes that run through it, the latitude and logitude of the station and ways to enter each station, whether the entrance/exit has a vending allow entrance, and ADA compliance.

The dataset is not really tidy enough. The `route` variable needs to be combined in some way.

``` r
nrow(distinct(nyc_transit, station_name, line))
```

    ## [1] 465

``` r
sum(nyc_transit$ada)
```

    ## [1] 468

``` r
vending_proportion = 100 * nrow(filter(nyc_transit, vending == "NO"))/nrow(nyc_transit)
```

The output shows that there are 465 distinct stations. 468 stations are ADA compliant. 9.8% of the entrance/exits is not vending allowed.

Problem 2
---------

``` r
mtw = read_excel("./data/HealthyHarborWaterWheelTotals2017-9-26.xlsx", 
                 sheet = 1, range = cell_cols("A:N")) %>% 
  janitor::clean_names() %>% 
  filter(dumpster != "NA")
mtw
```

    ## # A tibble: 216 x 14
    ##    dumpster month  year date                weight_tons volume_cubic_ya~
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>            <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31               18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74               13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45               15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06               18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71               13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52               14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76               18
    ## # ... with 206 more rows, and 8 more variables: plastic_bottles <dbl>,
    ## #   polystyrene <dbl>, cigarette_butts <dbl>, glass_bottles <dbl>,
    ## #   grocery_bags <dbl>, chip_bags <dbl>, sports_balls <dbl>,
    ## #   homes_powered <dbl>
